DASH_APP:
  APP_TITLE: Rainfall Stations Explorer
  UPDATE_TITLE: Updating...
  DEBUG: False

TEMPLATE:
  WATERMARK_SOURCE: 
  SHOW_LEGEND_INSIDE: False
  THEME: BOOTSTRAP

VERSION: v3.2.0
GITHUB_LINK: https://github.com/taruma/demo-stations
GITHUB_REPO: taruma/demo-stations

DATASET:
  METADATA: data/metadata # IGNORED IN run_metadata.py
  RAINFALL: data/rainfall
  COMPLETENESS: data/completeness

APP:
  MAPBOX_TOKEN: 