name: fiako-stations
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - dash-auth>=2.3
  - dash-bootstrap-components>=1.6
  - dash-bootstrap-templates>=1.1
  - dash>=2.16
  - geopy>=2.4
  - pandas>=2.2
  - plotly>=5.19
  - pytables>=3.9
  - python-box>=7.1
  - pyyaml>=6.0
